### PR TITLE
Add support for placeholder "nesting" for a sequence of selectors.

### PR DESCRIPTION
**Pull request by michelle**
This adds support for placeholders in a sequence of selectors (http://www.w3.org/TR/css3-selectors/#sequence).

As the `%` character cannot be used in a valid simple selector name, we can avoid the first group match for these placeholders to enable a more powerful nesting functionality.

I've also added tests to show the intended behavior.

### CODE REVIEW

**Comment by jonathanong** [comment]
i'm not using this anymore and i don't think anyone else is really maintaining this. i'm going to add you as a collab. feel free to push and publish.

**Comment by jonathanong** [comment]
let me know if you wanna help maintain any other plugins

**Comment by SlexAxton** [comment]
Can I be a collab too?

**Comment by jonathanong** [comment]
you sir can be an owner

**Pull request merged**
