### PR TITLE
Allow attribute selectors

### PR DESCRIPTION
**Pull request by valpackett**
As in:

``` css
%button[disabled] { cursor: not-allowed; }
.button { inherit: %button; }
```

### CODE REVIEW

**Comment by valpackett** [comment]
hey @michelle ? :-)

**Comment by michelle** [comment]
ACK, will take a look today. Thanks for the PR!

On Wednesday, August 20, 2014, Greg V notifications@github.com wrote:

> hey @michelle https://github.com/michelle ? :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reworkcss/rework-inherit/pull/14#issuecomment-52782948
> .

## 

Sent from Gmail Mobile

**Comment by michelle** [comment]
Could you add a test?

**Comment by valpackett** [comment]
Sure! Sorry, didn't notice the project had tests, edited quickly in github's web editor :D

**Comment by kevva** [comment]
Squasshhhh.

**Comment by michelle** [comment]
Squashed & merged.

**Pull request closed without merging**
